services:
  twitch:
    image: rdavidoff/twitch-channel-points-miner-v2
    ports:
      - "5000:5000"   
    stdin_open: true # docker run -i
    tty: true        # docker run -t 
    volumes:
      - type: bind
        source: /home/inatie/twitch/analytics
        target: /usr/src/app/analytics
        read_only: false
      - type: bind
        source: /home/inatie/twitch/cookies
        target: /usr/src/app/cookies
        read_only: false
      - type: bind
        source: /home/inatie/twitch/logs
        target: /usr/src/app/logs
        read_only: false
      - type: bind
        source: /home/inatie/twitch/run.py
        target: /usr/src/app/run.py
        read_only: false
  deploy:
    mode: replicated
    replicas: 1
      